### ISSUE TITLE
module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'

### ISSUE THREAD

**Issue by xcodebuild** [InternLM/OpenAOE#64]
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/openaoe", line 5, in <module>
    from openaoe.main import main
  File "/opt/homebrew/lib/python3.11/site-packages/openaoe/main.py", line 10, in <module>
    from openaoe.backend.api.route_google import router as google
  File "/opt/homebrew/lib/python3.11/site-packages/openaoe/backend/api/route_google.py", line 4, in <module>
    from openaoe.backend.service.service_google import palm_chat_svc
  File "/opt/homebrew/lib/python3.11/site-packages/openaoe/backend/service/service_google.py", line 1, in <module>
    from jsonstreamer import ObjectStreamer
  File "/opt/homebrew/lib/python3.11/site-packages/jsonstreamer/__init__.py", line 9, in <module>
    from jsonstreamer.jsonstreamer import JSONStreamer, ObjectStreamer
  File "/opt/homebrew/lib/python3.11/site-packages/jsonstreamer/jsonstreamer.py", line 12, in <module>
    from again import events
  File "/opt/homebrew/lib/python3.11/site-packages/again/__init__.py", line 4, in <module>
    from .events import EventSource, AsyncEventSource
  File "/opt/homebrew/lib/python3.11/site-packages/again/events.py", line 42, in <module>
    class AsyncEventSource(ListenerRegister):
  File "/opt/homebrew/lib/python3.11/site-packages/again/events.py", line 46, in AsyncEventSource
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?
```

**Comment by fly2tomato** [comment]
it seems to like  [this issue](https://github.com/InternLM/OpenAOE/issues/61)
