### ISSUE TITLE
No module named 'openaoe.backend.util.convert'

### ISSUE THREAD

**Issue by tonysy** [InternLM/OpenAOE#69]
```
$ python -m openaoe.main -f openaoe/backend/config/config-template.yaml
Traceback (most recent call last):
  File "/Users/zhangsongyang/miniconda3/envs/openaoe/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/zhangsongyang/miniconda3/envs/openaoe/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/zhangsongyang/Projects/OpenAOE/openaoe/main.py", line 15, in <module>
    from openaoe.backend.api.route_mistral import router as mistral
  File "/Users/zhangsongyang/Projects/OpenAOE/openaoe/backend/api/route_mistral.py", line 3, in <module>
    from openaoe.backend.service.mistral import Mistral
  File "/Users/zhangsongyang/Projects/OpenAOE/openaoe/backend/service/mistral.py", line 11, in <module>
    from openaoe.backend.util.convert import body_convert
ModuleNotFoundError: No module named 'openaoe.backend.util.convert'
```

**Comment by twpengit** [comment]
try to clone source code from branch v0.0.6
